export const BANK_BOOK_INIT = {
    facilityBusinessId: null,
    bankbookId: null,
    sort: null,
    type: null,
    bankbookNumber: null,
    bankbookNickname: '',
    classification: 'C',
    useType: 1,
    owner: '',
    accountCode: '',
    accountName: '',
    useScrap: true,
    createdAt: null,
    createdBy: '',
    updatedAt: null,
    updatedBy: '',
    ip: '',
    active: true,
    lastScrapingStatus: {
        lastScrapingDate: null,
        scrapingStatus: null,
        errorMessage: null,
    },
}
export const DATA_DETAIL_BANKBOOK = {
  companyId: null,
  fiscalYear: null,
  facilityBusinessId: null,
  bankbookId: null,
  bankbookInput: {
    bankbookNickname: '',
    useType: 1,
    owner: '',
    useScrap: true,
    sort: null,
    type: null,
    bankbookNumber: null,
    classification: '',
    accountCode: '',
    accountName: '',
  },
  scrapingInfoInput: {
    accountPassword: null,
    birthday: '',
    bizNumber: null,
    webId: '',
    webPassword: '',
  },
}
export const newSampleID = 'newSampleID'
