import gql from "graphql-tag";
export default gql`
    query
    getMyCompanyAutoGeneratedSeal(
            $name: String!   
        ){
            getMyCompanyAutoGeneratedSeal(name : $name) {
                name
                type
                seal
            }
        }`