interface Origindata {
    page: number,
    rows: number,
    statuses: number[],
    grade: null | number,
    name: string,
    code: string,
}
export const origindata: Origindata = {
    page: 1,
    rows: 10,
    statuses: [1],
    grade: null,
    name: "",
    code: "",
}

export const ArrForeigner = [{ id: false, text: '내국인' }, { id: true, text: '외국인' }] 

export const valueDefaultAction = {
    employeeId: null,
    name: '',
    foreigner: false,
    nationality: '대한민국',
    nationalityCode: 'KR',
    stayQualification: 'C-4',
    residentId: '',
    incomeTypeCode: '940100',
    incomeTypeName: '저술가',
    email: '',
}

export const dataDemo =
{
    totalTaxPay: "totalTaxPay",
    totalTaxfreePay: "totalTaxfreePay",
    withholdingIncomeTax: "221312",
    withholdingLocalIncomeTax: "22222",
    employee:
        [
            {
                employeeId: 28,
                type: "2",
                incomeTypeCode: "940905",
                name: "An Tú",
                foreigner: true,
                nationality: "2",
                nationalityCode: "2",
                stayQualification: "2",
                residentIdValidity: "2",
                roadAddress: "2",
                addressExtend: "2",
                email: "phamantu123@gmail.com",
                department: "2",
                responsibility: "2",
                status: 10,
                withholdingIncomeTax: "withholdingIncomeTax",
                withholdingLocalIncomeTax: "withholdingLocalIncomeTax",
                withholdingRuralSpecialTax: "2",
                createdAt: "2",
                createdBy: "2",
                updatedAt: "2",
                updatedBy: "2",
                ip: "2",
                active: "2",
                residentId: "990128-4654",
                joinedAt: "2",
                leavedAt: "2",
                retirementIncome: "2",
                weeklyWorkingHours: "2",
                monthlyPaycheck: "2",
                workingDays: "2",
                dailyWage: "2",
                monthlyWage: "2",
                totalDeduction: "2",
                deletable: "2",
            },
            {
                employeeId: 29,
                type: "2",
                incomeTypeCode: "940907",
                name: "An AM AN",
                foreigner: false,
                nationality: "2",
                nationalityCode: "2",
                stayQualification: "2",
                residentIdValidity: "2",
                roadAddress: "2",
                addressExtend: "2",
                email: "",
                department: "2",
                responsibility: "2",
                status: 10,
                withholdingIncomeTax: "withholdingIncomeTax",
                withholdingLocalIncomeTax: "withholdingLocalIncomeTax",
                withholdingRuralSpecialTax: "2",
                createdAt: "2",
                createdBy: "2",
                updatedAt: "2",
                updatedBy: "2",
                ip: "2",
                active: "2",
                residentId: "990128-4654",
                joinedAt: "2",
                leavedAt: "2",
                retirementIncome: "2",
                weeklyWorkingHours: "2",
                monthlyPaycheck: "2",
                workingDays: "2",
                dailyWage: "2",
                monthlyWage: "2",
                totalDeduction: "2",
                deletable: "2",
            }
        ],

}

