<template>
  <div :style="[
    heightHidden ? { height: heightHidden, overflow: 'hidden' } : {},
    !!width ? `max-width: ${width}px; width: 100%` : ''
  ]">
    <div class="upload-pewview-image">
      <a-upload list-type="picture-card" :multiple="multiple" v-model:file-list="fileList" @preview="handlePreview"
        headers="dsadasdsad" @change="changeFile" :customRequest="customRequest" :before-upload="beforeUpload" @remove="remove"
        accept="image/png, image/jpeg, image/jpg image/gif">
        <div v-if="fileList.length < limit">
          <div class="ant-btn-upload">
            <p class="ant-btn-upload-text">이미지 파일을 여기에 끌이다 놓으세요</p>
            <img src="@/assets/images/iconImage.png" class="ant-btn-upload-image" alt="">
            <p class="ant-btn-upload-text">또는</p>
            <button class="ant-btn-upload-button">파일 선택</button>
          </div>
        </div>
      </a-upload>
      <a-modal :visible="previewVisible" :footer="null" @cancel="handleCancel">
        <img alt="example" style="width: 100%; margin-top: 20px" :src="previewImage" />
      </a-modal>
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent, ref, watch, computed } from "vue";
import { useStore } from 'vuex';
import { useMutation, useQuery } from "@vue/apollo-composable";
import { companyId } from "@/helpers/commonFunction"
import queries from "@/graphql/queries/AC/AC1/AC110";
import mutations from "@/graphql/mutations/AC/AC1/AC110";
import mutationsUpload from "@/graphql/mutations/CM/CM110";
import notification from '@/utils/notification';
import { Message } from "@/configs/enum"
interface FileItem {
  uid: string;
  name?: string;
  status?: string;
  response?: string;
  percent?: number;
  url?: string;
  preview?: string;
  originFileObj?: any;
  fileStorageId?: any
}

interface FileInfo {
  file: FileItem;
  fileList: FileItem[];
}
export default defineComponent({
  props: {
    limit: {
      type: Number,
      default: 8
    },
    listImageFile: {
      type: Array,
      default: []
    },
    multiple: {
      type: Boolean,
      default: false
    },
    width: {
      type: String,
      default: ""
    },
    heightHidden: {
      type: String,
      default: ""
    },
    payLoadProofs: {
      type: Object,
      default: () => { }
    }
  },
  setup(props, { emit }) {
    const store = useStore();
    let fileList = ref<any[]>([])
    let isFailUpload = ref(false)
    const previewImage = ref<string | undefined>('');
    const previewVisible = ref<boolean>(false);
    let triggerBankbookDetailProofs = ref(false);
    let listFileStorageId = ref<any>([])
    // const globalYear = computed(() => store.state.settings.globalYear)
    // const globalFacilityBizId = computed(() => store.state.settings.globalFacilityBizId)

    // computed
    const payload = computed(() => props.payLoadProofs)
    // graphQL
    // queries
    const {
      result: resGetBankbookDetailProofs,
      // onResult: onResGetBankbookDetailProofs,
      loading: loadingGetBankbookDetailProofs,
      // refetch,
      // onError
    } = useQuery(queries.getBankbookDetailProofs, payload.value,
      () => ({
        enabled: triggerBankbookDetailProofs.value,
        fetchPolicy: "no-cache",
      }))

    // mutations
    const {
      mutate: addBankbookDetailProof,
      onDone: doneAddBankbookDetailProof,
      onError: errorAddBankbookDetailProof,
      loading: loadingAddBankbookDetailProof,
    } = useMutation(mutations.addBankbookDetailProof);
    doneAddBankbookDetailProof((e) => {
      notification('success', Message.getMessage('COMMON', '106').message)
    })
    errorAddBankbookDetailProof(e => {
      notification('error', e.message)
    })
    const {
      mutate: UploadImage,
      onDone: doneUploadImage,
      onError: errorUploadImage,
      loading: loadingUploadImage,
    } = useMutation(mutationsUpload.createMyCompanyAutoGeneratedSeal);
    doneUploadImage((e) => {
      listFileStorageId.value.push({
        ...fileList.value[fileList.value.length - 1], fileStorageId: e.data.createMyCompanyAutoGeneratedSeal
      })
      emit("update:listImageFile", listFileStorageId.value)
      addBankbookDetailProof({
        ...props.payLoadProofs,
        fileStorageId: e.data.createMyCompanyAutoGeneratedSeal
      })
    })
    errorUploadImage(e => {
      notification('error', e.message)
    })

    const {
      mutate: removeBankbookDetailProof,
      onDone: doneRemoveBankbookDetailProof,
      onError: errorRemoveBankbookDetailProof,
      loading: loadingRemoveBankbookDetailProof,
    } = useMutation(mutations.removeBankbookDetailProof);
    doneRemoveBankbookDetailProof((e) => {
      notification('success', Message.getMessage('COMMON', '106').message)
    })
    errorRemoveBankbookDetailProof(e => {
      notification('error', e.message)
    })
    // watch
    watch(() => props.listImageFile, (value) => {
      fileList.value = value
    })

    watch(() => resGetBankbookDetailProofs, (value) => {

    })

    watch(() => props.payLoadProofs, (value) => {
      if (!!value?.bankbookDetailId && !!value?.bankbookDetailDate) {
        triggerBankbookDetailProofs.value = true
      }
    })

    const getBase64 = (file: File) => {
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => resolve(reader.result);
        reader.onerror = error => reject(error);
      });
    }
    const handlePreview = async (file: FileItem) => {
      if (!file.url && !file.preview) {
        file.preview = (await getBase64(file.originFileObj)) as string;
      }
      previewImage.value = file.url || file.preview;
      previewVisible.value = true;
    };
    const handleCancel = () => {
      previewVisible.value = false;
    };

    const changeFile = ({ file, fileList: newFileList }: FileInfo) => {
    }

    const beforeUpload = (file: any) => {
      const isImage = file.type === 'image/jpeg' || file.type === 'image/png' || file.type === 'image/gif' || file.type === 'image/jpg'
      if (!isImage) {
        notification('error', 'You can only upload png, jpg, jpeg, gif file!')
      }
      const isLt10M = file.size / 1024 / 1024 <= 10;
      if (!isLt10M) {
        notification('error', 'Image must smaller than 10MB!')
      }
      const isDuplicaseName = fileList.value.some((items: any) => file.name === items.name)
      if (isDuplicaseName) {
        notification('error', 'Duplicate image are not allowed!')
      }
      isFailUpload.value = isImage && isLt10M && !isDuplicaseName
    };

    const customRequest = async (e: any) => {
      if (!isFailUpload.value) {
        fileList.value.splice(fileList.value.length - 1, 1)
        e.onError("");
        emit("update:listImageFile", listFileStorageId.value)
        return
      }
      e.onSuccess("ok");
      const basr64 =  await getBase64(e.file)
      // const res = await UploadImage({
      //   companyId: companyId,
      //   seal: basr64
      // })
      // if(res) {
      //   e.onSuccess("ok");
      // }else {
      //   e.onError("");
      // }
    }
    const remove = (e:any) => {
      const index = listFileStorageId.value.findIndex((item: any) => item.name === e.name)
      removeBankbookDetailProof({
        ...props.payLoadProofs,
        fileStorageId: listFileStorageId.value[index].fileStorageId
      })
      listFileStorageId.value.splice(index, 1)
      emit("update:listImageFile", listFileStorageId.value)
    }
    return {
      handlePreview,
      beforeUpload,
      previewVisible,
      fileList,
      handleCancel,
      previewImage,
      changeFile,
      customRequest,
      remove
    }
  }
})

</script>
<style lang="scss">
.upload-pewview-image {
  .ant-upload-list-picture-card-container {
    width: 120px;
    height: 120px;
  }

  .ant-upload-list-item {
    border-radius: 15px;
  }

  .ant-upload.ant-upload-select-picture-card {
    width: 120px;
    height: 120px;
    border-radius: 15px;
    margin: 0;
  }

  .ant-btn-upload {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;

    &-text {
      font-size: 11px;
    }

    &-image {
      width: 25px;
      margin: 5px 0;
    }

    &-button {
      font-size: 11px;
      background-color: #4472C4;
      border: none;
      outline: none;
      color: #fff;
      border-radius: 5px;
      padding: 0 15px;
    }
  }
}
</style>
