import getElectronicFilingsByIncomeWageDailyPaymentStatement from "./getElectronicFilingsByIncomeWageDailyPaymentStatement"
import searchIncomeWageDailyPaymentStatementElectronicFilings from "./searchIncomeWageDailyPaymentStatementElectronicFilings"
import getCompaniesInElectronicFilingFile from "./../BF630/getCompaniesInElectronicFilingFile"
import searchElectronicFilingFileProductions from "./../BF630/searchElectronicFilingFileProductions"
const queries = {
    getElectronicFilingsByIncomeWageDailyPaymentStatement: getElectronicFilingsByIncomeWageDailyPaymentStatement,
    searchIncomeWageDailyPaymentStatementElectronicFilings: searchIncomeWageDailyPaymentStatementElectronicFilings,
    searchElectronicFilingFileProductions: searchElectronicFilingFileProductions,
    getCompaniesInElectronicFilingFile: getCompaniesInElectronicFilingFile
};

export default queries;
