export const initialFormState = {
    status: 1,
    name: "",
    grade: 1,
    bizType: 2,
    bizNumber: "",
    residentId: "",
    email: "",
    mobilePhone: "",
    phone: "",
    fax: "",
    zipcode: "",
    roadAddress: "",
    jibunAddress: "",
    addressExtend: "",
    addressDetail: {
        bcode: "",
        bname: "",
        buildingCode: "",
        buildingName: "",
        roadname: "",
        roadnameCode: "",
        sido: "",
        sigungu: "",
        sigunguCode: "",
        zonecode: "",
    },
    taxInvoice: true,
    emailTaxInvoice: "",
    bankType: "39",
    accountNumber: "",
    accountOwner: "",
    registerDate: new Date(),
    cancelDate: "",
    remark: "",
};

interface Origindata {
    page: number,
    rows: number,
    statuses: number[],
    grade: null | number,
    name: string,
    code: string,
}
export const origindata : Origindata = {
    page: 1,
    rows: 20,
    statuses: [1],
    grade: null,
    name: "",
    code: "",
}