export const formState340 = {
    id: '',
    code: '',
    status: 0,
    name: '',
    address: '',
    grade: 0,
    phone: '',
    mobilePhone: '',
    registerDate: '',
    cancelDate: null,

    detailStatus: 0,
    detailName: '',
    detailGrade: 0,
    detailBizType: 0,
    detailBizNumber: '',
    detailResidentId: null,
    detailEmail: '',
    detailMobilePhone: '',
    detailPhone: '',
    detailFax: '',
    detailZipcode: '',
    detailRoadAddress: '',
    detailJibunAddress: '',
    detailAddressExtend: '',

    detailAddressDetailBcode: '',
    detailAddressDetailBname: '',
    detailAddressDetailBuildingCode: '',
    detailAddressDetailBuildingName: '',
    detailAddressDetailRoadname: '',
    detailAddressDetailRoadnameCode: '',
    detailAddressDetailSido: '',
    detailAddressDetailSigungu: '',
    detailAddressDetailSigunguCode: '',
    detailAddressDetailZonecode: '',

    detailTaxInvoice: false,
    detailEmailTaxInvoice: '',
    detailBankType: '',
    detailAccountNumber: '',
    detailAccountOwner: '',
    detailRegisterDate: '',
    detailCancelDate: '',
    detailRemark: '',

    createdAt: 0,
    createdBy: '',
    updatedAt: 0,
    updatedBy: '',
    ip: '',
    active: false,
}

interface Origindata {
    page: number,
    rows: number,
    statuses: number[],
    grade: null | number,
    name: string,
    code: string,
}
export const origindata : Origindata = {
    page: 1,
    rows: 10,
    statuses: [1],
    grade: null,
    name: "",
    code: "",
}