import WotkWithholdingMajorInsuranceConsignStatusManageScreenResolver from "./WotkWithholdingMajorInsuranceConsignStatusManageScreenResolver";
import getMajorInsuranceConsignStatusFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA860/getMajorInsuranceConsignStatusFaxFilingReportViewUrl";
import getMajorInsuranceCompanyJoinFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA870/getMajorInsuranceCompanyJoinFaxFilingReportViewUrl";
import getMajorInsuranceCompanyOutFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA880/getMajorInsuranceCompanyOutFaxFilingReportViewUrl";
import getMajorInsuranceCompanyEmployeeAcquisitionFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA810/getMajorInsuranceCompanyEmployeeAcquisitionFaxFilingReportViewUrl";
import getMajorInsuranceCompanyEmployeeLossFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA820/getMajorInsuranceCompanyEmployeeLossFaxFilingReportViewUrl";
import getMajorInsuranceCompanyEmployeeSalaryChangeFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA830/getMajorInsuranceCompanyEmployeeSalaryChangeFaxFilingReportViewUrl";
import getMajorInsuranceCompanyEmployeeLeaveOfAbsenceFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA840/getMajorInsuranceCompanyEmployeeLeaveOfAbsenceFaxFilingReportViewUrl";
import getMajorInsuranceCompanyEmployeeReturnToWorkFaxFilingReportViewUrl from "@/graphql/queries/PA/PA8/PA840/getMajorInsuranceCompanyEmployeeReturnToWorkFaxFilingReportViewUrl";
import getMajorInsuranceAdminCompanyRequestList from "./getMajorInsuranceAdminCompanyRequestList";
import getMajorInsuranceAdminCompanyEmployeeRequestList from "./getMajorInsuranceAdminCompanyEmployeeRequestList";
import getMajorInsuranceAdminConsignStatus from "./getMajorInsuranceAdminConsignStatus";
const queries = {
  WotkWithholdingMajorInsuranceConsignStatusManageScreenResolver,
  getMajorInsuranceAdminConsignStatus,
  getMajorInsuranceConsignStatusFaxFilingReportViewUrl,
  getMajorInsuranceAdminCompanyRequestList,
  getMajorInsuranceCompanyJoinFaxFilingReportViewUrl,
  getMajorInsuranceCompanyOutFaxFilingReportViewUrl,
  getMajorInsuranceAdminCompanyEmployeeRequestList,
  getMajorInsuranceCompanyEmployeeAcquisitionFaxFilingReportViewUrl,
  getMajorInsuranceCompanyEmployeeLossFaxFilingReportViewUrl,
  getMajorInsuranceCompanyEmployeeSalaryChangeFaxFilingReportViewUrl,
  getMajorInsuranceCompanyEmployeeLeaveOfAbsenceFaxFilingReportViewUrl,
  getMajorInsuranceCompanyEmployeeReturnToWorkFaxFilingReportViewUrl,
  
};

export default queries;
