import dayjs from "dayjs";
const statesPA120 = {
  actionFormDonePA120: 1,
  actionFormErrorPA120: 1,
  activeTabEditKeyPA120: '1',
  isForeignerPA120: false,
  presidentEditPA120: false,
  isDisableInsuranceSupport: false,
  yearPA120: +dayjs().format("YYYY"),
  notDatasourcePA120:false,
  deductionDependentCountPA120: 1,
  presidentOriginPA120:false,
  employeeIdPA120: null,
  createSucessTab1PA120: false,
  formStateTab1PA120: {
    name: null,
    foreigner: false,
    nationality: null,
    nationalityCode: "KR",
    stayQualification: null,
    residentId: "",
    roadAddress: null,
    addressExtend: null,
    email: null,
    employeeId: null,
    president: false,
    householder: false,
    weeklyWorkingHours: 40,
    department: null,
    responsibility: null,
    joinedAt: dayjs().format("YYYYMMDD"),
    leavedAt: null,
    key: "0",
},
  formOriginTab1PA120: {
    name: null,
    foreigner: false,
    nationality: null,
    nationalityCode: "KR",
    stayQualification: null,
    residentId: "",
    roadAddress: null,
    addressExtend: null,
    email: null,
    employeeId: 0,
    president: false,
    householder: false,
    weeklyWorkingHours: 40,
    department: null,
    responsibility: null,
    joinedAt: dayjs().format("YYYYMMDD"),
    leavedAt: null,
    key: "0"
  },
  formStateTab2PA120: {
    nationalPensionDeduction: false,
    healthInsuranceDeduction: false,
    longTermCareInsuranceDeduction: false,
    employeementInsuranceDeduction: false,
    insuranceSupport: false,
    employeementReduction: false,
    incomeTaxMagnification: 100,
    payItems: [],
    deductionItems: [],
  },
  formOriginTab2PA120: {
    nationalPensionDeduction: false,
    healthInsuranceDeduction: false,
    longTermCareInsuranceDeduction: false,
    employeementInsuranceDeduction: false,
    insuranceSupport: false,
    employeementReduction: false,
    incomeTaxMagnification: 100,
    payItems: [],
    deductionItems: [],
  },

  isNewRowPA120: false,
  deductionItemsPA120: [],
  payItemsPA120: [],
};

export default statesPA120;
