import dayjs from "dayjs";
const statesPA120 = {
  arrayRoweditedPA120: [],
  actionFormDonePA120: 1,
  actionFormErrorPA120: 1,
  keyActivePA120: 0,
  activeTabEditKeyPA120: '1',
  activeTabAddKeyPA120: '1',
  isForeignerPA120: false,
  presidentPA120: false,
  presidentEditPA120: false,
  isDisableInsuranceSupport: false,
  yearPA120: +dayjs().format("YYYY"),
  notDatasourcePA120:false,
  deductionDependentCountPA120: 1,
  presidentOriginPA120:false,
  initFormStateTabPA120: {
    name: null,
    foreigner: false,
    nationality: null,
    nationalityCode: "KR",
    stayQualification: null,
    residentId: "",
    roadAddress: null,
    addressExtend: null,
    email: null,
    employeeId: null,
    president: false,
    householder: false,
    weeklyWorkingHours: 40,
    department: null,
    responsibility: null,
    joinedAt: dayjs().format("YYYYMMDD"),
    leavedAt: null,
    key: "0"
},
  editRowPA120: {
    name: null,
    foreigner: false,
    nationality: null,
    nationalityCode: "KR",
    stayQualification: null,
    residentId: "",
    roadAddress: null,
    addressExtend: null,
    email: null,
    employeeId: 0,
    president: false,
    householder: false,
    weeklyWorkingHours: 40,
    department: null,
    responsibility: null,
    joinedAt: dayjs().format("YYYYMMDD"),
    leavedAt: null,
    key: "0"
  },
  initFormTab2PA120: {
    nationalPensionDeduction: false,
    healthInsuranceDeduction: false,
    longTermCareInsuranceDeduction: false,
    employeementInsuranceDeduction: false,
    insuranceSupport: false,
    employeementReduction: false,
    incomeTaxMagnification: 100,
    payItems: [],
    deductionItems: [],
  },
  editRowTab2PA120: {
    nationalPensionDeduction: false,
    healthInsuranceDeduction: false,
    longTermCareInsuranceDeduction: false,
    employeementInsuranceDeduction: false,
    insuranceSupport: false,
    employeementReduction: false,
    incomeTaxMagnification: 100,
    payItems: [],
    deductionItems: [],
  },

  isCompareEditPA120: true,
  isNewRowPA120: false,
  isAddFormErrorPA120: false,
  isChangeConfigPayItemsPA120: false,
  isCalculateEditPA120: true,
};

export default statesPA120;
