<template>
  <p style="font-size: 18px;font-weight: 500;margin: 20px;"> This is the table created by the library <a href="https://handsontable.com/demo" target="_blank">handsontable</a> </p>
  <hot-table :settings="hotSettings"></hot-table>
</template>

<script>
import { defineComponent } from "vue";
import { HotTable } from "@handsontable/vue3";
import { registerAllModules } from "handsontable/registry";
import "handsontable/dist/handsontable.full.css";
import filters from "@/helpers/filters";

// register Handsontable's modules
registerAllModules();
const firstRowRenderer = (instance, td, row, col, prop, value, cellProperties)=>{
  if (row === 4) {
      td.style.fontWeight = 'bold';
      td.innerHTML = `<p style="color:red;margin: unset;float: right;">${filters.formatCurrency(parseInt(cellProperties.oldValue))}</p><p style="margin: unset;float: right;">${filters.formatCurrency(parseInt(value))}</p>`
      return td;
    }
  }
export default defineComponent({
  data() {
    return {
      hotSettings: {
        comments: true,
        fillHandle: true,
         colWidths: 100,
        height: 120,
        beforeKeyDown: function (e) {
          var reg = /\D/g;
          if (reg.test(e.key)) {
            e.preventDefault()
          }
        },
        data: [
          ["1. 원천징수 내역 및 납부세액", "", "", "", "", "", "", "", "", "", "", "", ""],
          ["", "소득자 소득구분", "", "", "코드", "원 천 징 수 명 세", "", "", "", "", "⑨<br> 당월 조정<br>환급세액", "납부 세액", ""],
          ["", "", "", "", "", "소 득 지 급 <br>(과세 미달, 비과세 포함)	", "", "징수세액", "", "", "", "⑩<br>소득세 등<br>(가산세 포함)", "⑪ <br>농어촌<br> 특별세"],
          ["", "", "", "", "", "④인원", "⑤총지급액", "⑥소득세 등", "⑦농어촌<br>특별세", "⑧가산세", "", "", ""],
          ["개<br>인<br>⁀<br>거주<br>자ㆍ<br>비거<br>주자<br>⌣", "근로<br>소득", "간이세액", "", "A01","300000", "", "", "", "", "", "", ""],
          ["", "", "중도퇴사", "", "A02", "", "", "", "", "", "", "", ""],
          ["", "", "일용근로", "", "A03", "", "", "", "", "", "", "", ""],
          ["", "", "연말<br>정산", "합계", "A04", "", "", "", "", "", "", "", ""],
          ["", "", "", "분납신청", "A05", "", "", "", "", "", "", "", ""],
          ["", "", "", "납부금액", "A06", "", "", "", "", "", "", "", ""],
          ["", "", "가감계", "", "A10", "", "", "", "", "", "", "", ""],
          ["", "퇴직<br>소득", "연금계좌", "", "A21", "", "", "", "", "", "", "", ""],
          ["", "", "그 외	", "", "A22", "", "", "", "", "", "", "", ""],
          ["", "", "가감계", "", "A20", "", "", "", "", "", "", "", ""],
          ["", "사업<br>소득", "매월징수", "", "A25", "", "", "", "", "", "", "", ""],
          ["", "", "연말정산", "", "A26", "", "", "", "", "", "", "", ""],
          ["", "", "가감계", "", "A30", "", "", "", "", "", "", "", ""],
          ["", "기타<br>소득", "연금계좌", "", "A41", "", "", "", "", "", "", "", ""],
          ["", "", "종교인<br>소득", "매월징수", "A43", "", "", "", "", "", "", "", ""],
          ["", "", "", "연말정산", "A44", "", "", "", "", "", "", "", ""],
          ["", "", "그 외", "", "A42", "", "", "", "", "", "", "", ""],
          ["", "", "가감계", "", "A40", "", "", "", "", "", "", "", ""],
          ["", "연<br>금<br>소<br>득", "연금계좌", "", "A48", "", "", "", "", "", "", "", ""],
          ["", "", "공적연금 매월 (매월)", "", "A45", "", "", "", "", "", "", "", ""],
          ["", "", "연말정산", "", "A46", "", "", "", "", "", "", "", ""],
          ["", "", "가감계", "", "A47", "", "", "", "", "", "", "", ""],
          ["", "이자소득", "", "", "A50", "", "", "", "", "", "", "", ""],
          ["", "배당소득", "", "", "A60", "", "", "", "", "", "", "", ""],
          ["", "저축 등 해지 추징세액 등", "", "", "A69", "", "", "", "", "", "", "", ""],
          ["", "비거주자 양도소득", "", "", "A70", "", "", "", "", "", "", "", ""],
          ["법인", "내ㆍ외국법인원천", "", "", "A80", "", "", "", "", "", "", "", ""],
          ["수정신고 세액 (세액)", "", "", "", "A90", "", "", "", "", "", "", "", ""],
          ["총 합 계", "", "", "", "A99", "", "", "", "", "", "", "", ""],
        ],
        mergeCells: [
          { row: 0, col: 0, rowspan: 1, colspan: 13 },

          { row: 1, col: 0, rowspan: 3, colspan: 1 },
          { row: 1, col: 1, rowspan: 3, colspan: 3 },
          { row: 1, col: 4, rowspan: 3, colspan: 1 },
          { row: 1, col: 5, rowspan: 1, colspan: 5 },
          { row: 1, col: 10, rowspan: 3, colspan: 1 },
          { row: 1, col: 11, rowspan: 1, colspan: 2 },

          { row: 2, col:5, rowspan: 1, colspan: 2 },
          { row: 2, col: 7, rowspan: 1, colspan: 3 },

          { row: 2, col:11, rowspan: 2, colspan: 1 },
          { row: 2, col: 12, rowspan: 2, colspan: 1 },

          { row: 4, col: 0, rowspan: 26, colspan: 1 },
          { row: 4, col: 1, rowspan: 7, colspan: 1 },
          { row: 4, col: 2, rowspan: 1, colspan: 2 },

          { row: 5, col: 2, rowspan: 1, colspan: 2 },

          { row: 6, col: 2, rowspan: 1, colspan: 2 },

          { row: 7, col: 2, rowspan: 3, colspan: 1 },

          { row: 10, col: 2, rowspan: 1, colspan: 2 },

          { row: 11, col: 1, rowspan: 3, colspan: 1 },
          { row: 11, col: 2, rowspan: 1, colspan: 2 },

          { row: 12, col: 2, rowspan: 1, colspan: 2 },
          { row: 13, col: 2, rowspan: 1, colspan: 2 },

          { row: 14, col: 1, rowspan: 3, colspan: 1 },
          { row: 14, col: 2, rowspan: 1, colspan: 2 },

          { row: 15, col: 2, rowspan: 1, colspan: 2 },
          { row: 16, col: 2, rowspan: 1, colspan: 2 },

          { row: 17, col: 1, rowspan: 5, colspan: 1 },
          { row: 17, col: 2, rowspan: 1, colspan: 2 },

          { row: 18, col: 2, rowspan: 2, colspan: 1 },
          { row: 20, col: 2, rowspan: 1, colspan: 2 },
          { row: 21, col: 2, rowspan: 1, colspan: 2 },
          { row: 22, col: 1, rowspan: 4, colspan: 1 },
          { row: 22, col: 2, rowspan: 1, colspan: 2 },
          { row: 23, col: 2, rowspan: 1, colspan: 2 },
          { row: 24, col: 2, rowspan: 1, colspan: 2 },
          { row: 25, col: 2, rowspan: 1, colspan: 2 },
          { row: 26, col: 1, rowspan: 1, colspan: 3 },
          { row: 27, col: 1, rowspan: 1, colspan: 3 },
          { row: 28, col: 1, rowspan: 1, colspan: 3 },
          { row: 29, col: 1, rowspan: 1, colspan: 3 },

          { row: 30, col: 1, rowspan: 1, colspan: 3 },
          { row: 31, col: 0, rowspan: 1, colspan: 4 },
          { row: 32, col: 0, rowspan: 1, colspan: 4 },
        ],
        cell: [
          { row: 0, col: 0, readOnly: true },

          { row: 1, col: 0, readOnly: true , className: 'htMiddle',},
          { row: 1, col: 1, readOnly: true , className: 'htCenter htMiddle' },
          { row: 1, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 1, col: 5, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 1, col: 10, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 1, col: 11, readOnly: true  , className: 'htCenter htMiddle'},

          { row: 2, col:5, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 2, col: 7, readOnly: true  , className: 'htCenter htMiddle'},

          { row: 2, col:11, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 2, col: 12, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},

          { row: 3, col: 5, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 3, col: 6, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 3, col: 7, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 3, col: 8, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 3, col: 9, readOnly: true  , className: 'htCenter htMiddle'},

          { row: 4, col: 0, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 4, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 4, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 4, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 5, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 5, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 6, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 6, col: 4, readOnly: true  , className: 'htCenter htMiddle'},

          { row: 7, col: 2, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 7, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 7, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 8, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 8, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 9, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 9, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 10, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 10, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 11, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 11, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 11, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 12, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 12, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 13, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 13, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 14, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 14, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 14, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 15, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 15, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 16, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 16, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 17, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 17, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 17, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 18, col: 2, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 18, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 18, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 19, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 19, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 20, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 20, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 21, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 21, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 22, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
          { row: 22, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 22, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 23, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 23, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 24, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 24, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 25, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 25, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 26, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 26, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 27, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 27, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 28, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 28, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 29, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 29, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 30, col: 0, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 30, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 30, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 31, col: 0, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 31, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 32, col: 0, readOnly: true  , className: 'htCenter htMiddle'},
          { row: 32, col: 4, readOnly: true  , className: 'htCenter htMiddle'},


          { oldValue:'220000', row: 4, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },renderer: firstRowRenderer},
          { row: 4, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 4, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 4, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 4, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 4, col: 10  , className: 'disable-cell',readOnly: true },
          { row: 4, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 4, col: 12  , className: 'disable-cell',readOnly: true },

          { row: 5, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 5, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 5, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 5, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 5, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 5, col: 10  , className: 'disable-cell',readOnly: true },
          { row: 5, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 5, col: 12  , className: 'disable-cell',readOnly: true },

          { row: 6, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 6, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 6, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 6, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 6, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 6, col: 10  , className: 'disable-cell',readOnly: true },
          { row: 6, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 6, col: 12  , className: 'disable-cell',readOnly: true },

          { row: 7, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 7, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 7, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 7, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 7, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 7, col: 10  , className: 'disable-cell',readOnly: true },
          { row: 7, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 7, col: 12  , className: 'disable-cell',readOnly: true },

          { row: 8, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 8, col: 6   , className: 'disable-cell',readOnly: true},
          { row: 8, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 8, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 8, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 8, col: 10  , className: 'disable-cell',readOnly: true },
          { row: 8, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 8, col: 12  , className: 'disable-cell',readOnly: true },

          { row: 9, col: 5   , className: 'disable-cell',readOnly: true},
          { row: 9, col: 6   , className: 'disable-cell',readOnly: true},
          { row: 9, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 9, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 9, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 9, col: 10  , className: 'disable-cell',readOnly: true },
          { row: 9, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 9, col: 12  , className: 'disable-cell',readOnly: true },

          { row: 10, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 10, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 10, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 10, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 10, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 10, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 10, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 10, col: 12  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},

          { row: 11, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 11, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 11, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 11, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 11, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 11, col: 10  , className: 'disable-cell',readOnly: true},
          { row: 11, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 11, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 12, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 12, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 12, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 12, col: 8 , className: 'disable-cell',readOnly: true},
          { row: 12, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 12, col: 10 , className: 'disable-cell',readOnly: true},
          { row: 12, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 12, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 13, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 13, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 13, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 13, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 13, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 13, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 13, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 13, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 14, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 14, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 14, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 14, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 14, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 14, col: 10  , className: 'disable-cell',readOnly: true},
          { row: 14, col: 11 , className: 'disable-cell',readOnly: true },
          { row: 14, col: 12 , className: 'disable-cell',readOnly: true},

          { row: 15, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 15, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 15, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 15, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 15, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 15, col: 10 , className: 'disable-cell',readOnly: true},
          { row: 15, col: 11 , className: 'disable-cell',readOnly: true},
          { row: 15, col: 12 , className: 'disable-cell',readOnly: true},

          { row: 16, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 16, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 16, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 16, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 16, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 16, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 16, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 16, col: 12  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},

          { row: 17, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 17, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 17, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 17, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 17, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 17, col: 10 , className: 'disable-cell',readOnly: true},
          { row: 17, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 17, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 18, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 18, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 18, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 18, col: 8 , className: 'disable-cell',readOnly: true},
          { row: 18, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 18, col: 10  , className: 'disable-cell',readOnly: true},
          { row: 18, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 18, col: 12 , className: 'disable-cell',readOnly: true},

          { row: 19, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 19, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 19, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 19, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 19, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 19, col: 10  , className: 'disable-cell',readOnly: true},
          { row: 19, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 19, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 20, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 20, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 20, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 20, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 20, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 20, col: 10  , className: 'disable-cell',readOnly: true},
          { row: 20, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 20, col: 12  , className: 'disable-cell',readOnly: true},
          
          { row: 21, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 21, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 21, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 21, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 21, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 21, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 21, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 21, col: 12 , className: 'disable-cell',readOnly: true},

          { row: 22, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 22, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 22, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 22, col: 8   , className: 'disable-cell',readOnly: true},
          { row: 22, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 22, col: 10   , className: 'disable-cell',readOnly: true},
          { row: 22, col: 11  , className: 'disable-cell',readOnly: true },
          { row: 22, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 23, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 23, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 23, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 23, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 23, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 23, col: 10 , className: 'disable-cell',readOnly: true},
          { row: 23, col: 11  , className: 'disable-cell',readOnly: true},
          { row: 23, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 24, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 24, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 24, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 24, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 24, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 24, col: 10  , className: 'disable-cell',readOnly: true},
          { row: 24, col: 11  , className: 'disable-cell',readOnly: true},
          { row: 24, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 25, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 25, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 25, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 25, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 25, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 25, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 25, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 25, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 26, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 26, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 26, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 26, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 26, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 26, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 26, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 26, col: 12  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},

          { row: 27, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 27, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 27, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 27, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 27, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 27, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 27, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 27, col: 12  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},

          { row: 28, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 28, col: 6  , className: 'disable-cell',readOnly: true},
          { row: 28, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 28, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 28, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 28, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 28, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 28, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 29, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 29, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 29, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 29, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 29, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 29, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 29, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 29, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 30, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 30, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 30, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 30, col: 8  , className: 'disable-cell',readOnly: true},
          { row: 30, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 30, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 30, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 30, col: 12  , className: 'disable-cell',readOnly: true},

          { row: 31, col: 5  , className: 'disable-cell',readOnly: true},
          { row: 31, col: 6  , className: 'disable-cell',readOnly: true},
          { row: 31, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 31, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 31, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 31, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 31, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 31, col: 12  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},

          { row: 32, col: 5  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }},
          { row: 32, col: 6  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 32, col: 7  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 32, col: 8  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 32, col: 9  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 32, col: 10  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
          { row: 32, col: 11  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' }, },
          { row: 32, col: 12  , className: 'htMiddle htRight' ,type: 'numeric',  numericFormat: {pattern: '0,0',culture: 'ko-KR' },},
        ],
        height: "auto",
        licenseKey: "non-commercial-and-evaluation",
      },
    };
  },
  components: {
    HotTable,
  },
});
</script>
<style lang="scss" scoped>
  ::v-deep td.disable-cell {
    color: #fff;
    background-color: #b3b4b3;
  }
</style>
