export const  mergeCells =  [
    { row: 0, col: 0, rowspan: 1, colspan: 13 },

    { row: 1, col: 0, rowspan: 3, colspan: 1 },
    { row: 1, col: 1, rowspan: 3, colspan: 3 },
    { row: 1, col: 4, rowspan: 3, colspan: 1 },
    { row: 1, col: 5, rowspan: 1, colspan: 5 },
    { row: 1, col: 10, rowspan: 3, colspan: 1 },
    { row: 1, col: 11, rowspan: 1, colspan: 2 },

    { row: 2, col:5, rowspan: 1, colspan: 2 },
    { row: 2, col: 7, rowspan: 1, colspan: 3 },

    { row: 2, col:11, rowspan: 2, colspan: 1 },
    { row: 2, col: 12, rowspan: 2, colspan: 1 },

    { row: 4, col: 0, rowspan: 26, colspan: 1 },
    { row: 4, col: 1, rowspan: 7, colspan: 1 },
    { row: 4, col: 2, rowspan: 1, colspan: 2 },

    { row: 5, col: 2, rowspan: 1, colspan: 2 },

    { row: 6, col: 2, rowspan: 1, colspan: 2 },

    { row: 7, col: 2, rowspan: 3, colspan: 1 },

    { row: 10, col: 2, rowspan: 1, colspan: 2 },

    { row: 11, col: 1, rowspan: 3, colspan: 1 },
    { row: 11, col: 2, rowspan: 1, colspan: 2 },

    { row: 12, col: 2, rowspan: 1, colspan: 2 },
    { row: 13, col: 2, rowspan: 1, colspan: 2 },

    { row: 14, col: 1, rowspan: 3, colspan: 1 },
    { row: 14, col: 2, rowspan: 1, colspan: 2 },

    { row: 15, col: 2, rowspan: 1, colspan: 2 },
    { row: 16, col: 2, rowspan: 1, colspan: 2 },

    { row: 17, col: 1, rowspan: 5, colspan: 1 },
    { row: 17, col: 2, rowspan: 1, colspan: 2 },

    { row: 18, col: 2, rowspan: 2, colspan: 1 },
    { row: 20, col: 2, rowspan: 1, colspan: 2 },
    { row: 21, col: 2, rowspan: 1, colspan: 2 },
    { row: 22, col: 1, rowspan: 4, colspan: 1 },
    { row: 22, col: 2, rowspan: 1, colspan: 2 },
    { row: 23, col: 2, rowspan: 1, colspan: 2 },
    { row: 24, col: 2, rowspan: 1, colspan: 2 },
    { row: 25, col: 2, rowspan: 1, colspan: 2 },
    { row: 26, col: 1, rowspan: 1, colspan: 3 },
    { row: 27, col: 1, rowspan: 1, colspan: 3 },
    { row: 28, col: 1, rowspan: 1, colspan: 3 },
    { row: 29, col: 1, rowspan: 1, colspan: 3 },

    { row: 30, col: 1, rowspan: 1, colspan: 3 },
    { row: 31, col: 0, rowspan: 1, colspan: 4 },
    { row: 32, col: 0, rowspan: 1, colspan: 4 },

    { row: 33, col: 0, rowspan: 1, colspan: 13 },
    { row: 34, col: 0, rowspan: 1, colspan: 5 },
    { row: 34, col: 5, rowspan: 1, colspan: 4 },
    { row: 34, col: 9, rowspan: 3, colspan: 1 },
    { row: 34, col: 10, rowspan: 3, colspan: 1 },
    { row: 34, col: 11, rowspan: 3, colspan: 1 },
    { row: 34, col: 12, rowspan: 3, colspan: 1 },
    { row: 35, col: 0, rowspan: 2, colspan: 2 },
    { row: 35, col: 2, rowspan: 2, colspan: 1 },
    { row: 35, col: 3, rowspan: 2, colspan: 2 },
    { row: 35, col: 5, rowspan: 2, colspan: 1 },
    { row: 35, col: 6, rowspan: 2, colspan: 1 },
    { row: 35, col: 7, rowspan: 1, colspan: 2 },
    { row: 36, col: 7, rowspan: 1, colspan: 1 },
    { row: 36, col: 8, rowspan: 1, colspan: 1 },
  ]

export const cellsSetting = [
    { row: 0, col: 0, readOnly: true },

    { row: 1, col: 0, readOnly: true , className: 'htMiddle',},
    { row: 1, col: 1, readOnly: true , className: 'htCenter htMiddle' },
    { row: 1, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 1, col: 5, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 1, col: 10, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 1, col: 11, readOnly: true  , className: 'htCenter htMiddle'},

    { row: 2, col:5, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 2, col: 7, readOnly: true  , className: 'htCenter htMiddle'},

    { row: 2, col:11, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 2, col: 12, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},

    { row: 3, col: 5, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 3, col: 6, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 3, col: 7, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 3, col: 8, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 3, col: 9, readOnly: true  , className: 'htCenter htMiddle'},

    { row: 4, col: 0, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 4, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 4, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 4, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 5, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 5, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 6, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 6, col: 4, readOnly: true  , className: 'htCenter htMiddle'},

    { row: 7, col: 2, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 7, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 7, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 8, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 8, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 9, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 9, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 10, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 10, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 11, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 11, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 11, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 12, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 12, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 13, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 13, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 14, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 14, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 14, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 15, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 15, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 16, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 16, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 17, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 17, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 17, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 18, col: 2, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 18, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 18, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 19, col: 3, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 19, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 20, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 20, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 21, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 21, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 22, col: 1, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 22, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 22, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 23, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 23, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 24, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 24, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 25, col: 2, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 25, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 26, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 26, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 27, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 27, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 28, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 28, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 29, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 29, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 30, col: 0, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 30, col: 1, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 30, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 31, col: 0, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 31, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 32, col: 0, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 32, col: 4, readOnly: true  , className: 'htCenter htMiddle'},
    { row: 34, col: 0, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 34, col: 0, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 34, col: 5, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 34, col: 9, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 34, col: 10, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 34, col: 11, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 34, col: 12, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 35, col: 0, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 35, col: 2, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 35, col: 3, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 35, col: 5, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 35, col: 6, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 35, col: 7, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 36, col: 7, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
    { row: 36, col: 8, readOnly: true  , className: 'htCenter htMiddle',renderer: 'html'},
]