import getCompaniesInElectronicFilingFile from  "@/graphql/queries/common/getCompaniesInElectronicFilingFile";
import searchIncomeWageSimplifiedPaymentStatementElectronicFilings from "./searchIncomeWageSimplifiedPaymentStatementElectronicFilings";
import searchIncomeBusinessSimplifiedPaymentStatementElectronicFilings from "./searchIncomeBusinessSimplifiedPaymentStatementElectronicFilings";
import searchElectronicFilingFileProductions from "./searchElectronicFilingFileProductions";
import getElectronicFilingsByIncomeWageSimplifiedPaymentStatement from "./getElectronicFilingsByIncomeWageSimplifiedPaymentStatement";
import getElectronicFilingsByIncomeBusinessSimplifiedPaymentStatement from "./getElectronicFilingsByIncomeBusinessSimplifiedPaymentStatement";

const queries = {
    searchIncomeWageSimplifiedPaymentStatementElectronicFilings: searchIncomeWageSimplifiedPaymentStatementElectronicFilings,
    searchIncomeBusinessSimplifiedPaymentStatementElectronicFilings: searchIncomeBusinessSimplifiedPaymentStatementElectronicFilings,
    searchElectronicFilingFileProductions: searchElectronicFilingFileProductions,
    getElectronicFilingsByIncomeWageSimplifiedPaymentStatement: getElectronicFilingsByIncomeWageSimplifiedPaymentStatement,
    getElectronicFilingsByIncomeBusinessSimplifiedPaymentStatement: getElectronicFilingsByIncomeBusinessSimplifiedPaymentStatement,
    getCompaniesInElectronicFilingFile: getCompaniesInElectronicFilingFile,
};

export default queries;
