export const sampleDataIncomeWage = {
  actualPayment: 0,
  monthlyWage: 0,
  dailyWage: 0,
  workingDays: null,
  paymentDay: null,
  deductionItems: [],
  employee: {
    employeeId: null,
    name: "",
    totalDeduction: 0,
    monthlyPaycheck: true,
  },
  totalPay: 0,
  totalPayItem: 0,
  totalPayItemTax: 0,
  totalPayItemTaxFree: 0,
  totalDeduction: 0,
  subPayment: 0,
  overtimeWorkingHours: null,
  totalWorkingHours: null,
  workingHoursAtNight: null,
  workingHoursOnHolidays: null,
  payItems: [],
  incomeId: "PA110",
};
export const initDataCustomRes = [
  { id: 1, name: "재직(퇴사)" },
  { id: 2, name: "과세급여" },
  { id: 3, name: "비과세급여" },
  { id: 4, name: "급여총액" },
  { id: 5, name: "국민연금" },
  { id: 6, name: "건강보험" },
  { id: 7, name: "장기요양" },
  { id: 8, name: "고용보험" },
  { id: 9, name: "소득세" },
  { id: 10, name: "지방소득세" },
  { id: 11, name: "공제총액" },
  { id: 12, name: "차인지급액" },
];
