import gql from "graphql-tag";
export default gql`
  query searchIncomeWageWithholdingReceipts(
    $companyId: Int!
    $filter: IncomeWageWithholdingReceiptSearchFilter!
  ) {
    searchIncomeWageWithholdingReceipts(
      companyId: $companyId
      filter: $filter
    ) {
      incomeId
      imputedMonth
      paymentYear
      paymentMonth
      paymentDay
      employeeType
      employeeId
      incomeTypeCode
      incomePayment
      withholdingIncomeTax
      withholdingLocalIncomeTax
      withholdingRuralSpecialTax
      prevPaymentDay
      createdAt
      createdBy
      updatedAt
      updatedBy
      ip
      active
      leaved
      annualEarnedIncome
      taxFreeIncome
      totalSalary
      earnedIncomeDeduction
      earnedIncomeAmount
      personalDeduction
      pensionPremiumDeduction
      specialIncomeDeduction
      otherIncomeDeduction
      taxStandard
      calculationTaxAmount
      taxReduction
      taxCredit
      decidedTaxAmount
      prePaidTaxAmount
      deductibleTaxAmount
      employee{
        type
        employeeId
        incomeTypeCode
        name
        foreigner
        nationality
        nationalityCode
        stayQualification
        residentIdValidity
        roadAddress
        addressExtend
        email
        department
        responsibility
        status
        withholdingIncomeTax
        withholdingLocalIncomeTax
        withholdingRuralSpecialTax
        createdAt
        createdBy
        updatedAt
        updatedBy
        ip
        active
        residentId
        joinedAt
        leavedAt
        president
        householder
        nationalPensionDeduction
        healthInsuranceDeduction
        longTermCareInsuranceDeduction
        employeementInsuranceDeduction
        insuranceSupport
        nationalPensionSupportPercent
        employeementInsuranceSupportPercent
        employeementReduction
        employeementReductionStartDate
        employeementReductionFinishDate
        employeementReductionRatePercent
        employeementReductionInput
        weeklyWorkingHours
        deductionDependentCount
        incomeTaxMagnification
        incomePayment
        totalPay
        totalDeduction
        deletable
        payItems{
          itemCode
          amount
        }
        deductionItems{
          itemCode
          amount
        }
        dependents{
          employeeId
          incomeTypeCode
          index
          relation
          name
          foreigner
          residentIdValidity
          basicDeduction
          women
          singleParent
          senior
          disabled
          maternityAdoption
          descendant
          consignmentRelationship
          householder
          residentId
        }
      }
    }
  }
`;
