import gql from "graphql-tag";
export default gql`
  query searchIncomeRetirementWithholdingReceipts(
    $companyId: Int!
    $filter: IncomeRetirementWithholdingReceiptSearchFilter!
  ) {
    searchIncomeRetirementWithholdingReceipts(
      companyId: $companyId
      filter: $filter
    ) {
      incomeId
      imputedMonth
      paymentYear
      paymentMonth
      paymentDay
      employeeType
      employeeId
      incomeTypeCode
      incomePayment
      withholdingIncomeTax
      withholdingLocalIncomeTax
      withholdingRuralSpecialTax
      prevPaymentDay
      createdAt
      createdBy
      updatedAt
      updatedBy
      ip
      active
      retirementType
      settlementStartDate
      settlementFinishDate
      retirementBenefits
      nonTaxableRetirementBenefits
      taxableRetirementBenefits
      totalDeduction
      specificationId
      actualPayment
      employee{
        ... on EmployeeWage {
          type
          employeeId
          incomeTypeCode
          name
          foreigner
          nationality
          nationalityCode
          stayQualification
          residentIdValidity
          roadAddress
          addressExtend
          email
          department
          responsibility
          status
          withholdingIncomeTax
          withholdingLocalIncomeTax
          withholdingRuralSpecialTax
          createdAt
          createdBy
          updatedAt
          updatedBy
          ip
          active
          residentId
          joinedAt
          leavedAt
          president
          householder
          nationalPensionDeduction
          healthInsuranceDeduction
          longTermCareInsuranceDeduction
          employeementInsuranceDeduction
          insuranceSupport
          nationalPensionSupportPercent
          employeementInsuranceSupportPercent
        }
        ... on EmployeeWageDaily {
          type
          employeeId
          incomeTypeCode
          name
          foreigner
          nationality
          nationalityCode
          stayQualification
          residentIdValidity
          roadAddress
          addressExtend
          email
          department
          responsibility
          status
          withholdingIncomeTax
          withholdingLocalIncomeTax
          withholdingRuralSpecialTax
          createdAt
          createdBy
          updatedAt
          updatedBy
          ip
          active
          residentId
          joinedAt
          leavedAt
          retirementIncome
          nationalPensionDeduction
          healthInsuranceDeduction
          longTermCareInsuranceDeduction
          employeementInsuranceDeduction
          insuranceSupport
          nationalPensionSupportPercent
          employeementInsuranceSupportPercent
          weeklyWorkingHours
          monthlyPaycheck
          workingDays
          dailyWage
          monthlyWage
          totalDeduction
          deletable
          deductionItems{
            itemCode
            amount
          }
        }
      }
      specification{
          id
          executive
          retirementReason
          totalPay3Month
          totalAnualBonus
          annualLeaveAllowance
          expectedRetirementBenefits
          definedRetirementBenefits
          nonTaxableRetirementBenefits
          taxableRetirementBenefits
          createdAt
          createdBy
          updatedAt
          updatedBy
          ip
          active
        }
      }
    }
`;
