import getMajorInsuranceCompanyEmployeeSalaryChanges from "./getMajorInsuranceCompanyEmployeeSalaryChanges";
import getMajorInsuranceCompanyEmployeeSalaryChange from "./getMajorInsuranceCompanyEmployeeSalaryChange";
import getMajorInsuranceCompanyEmployeeLossLogs from "./getMajorInsuranceCompanyEmployeeLossLogs";
import getMajorInsuranceCompanyEmployeeSalaryChangeFaxFilingReportViewUrl from "./getMajorInsuranceCompanyEmployeeSalaryChangeFaxFilingReportViewUrl";

export default {
  getMajorInsuranceCompanyEmployeeSalaryChanges,
  getMajorInsuranceCompanyEmployeeSalaryChange,
  getMajorInsuranceCompanyEmployeeLossLogs,
  getMajorInsuranceCompanyEmployeeSalaryChangeFaxFilingReportViewUrl,
};
