import dayjs from "dayjs";

export const initialState = {
  id: null,
  info: {
    totalPrice: 0,
    accountingPrice: 0,
    withholdingPrice: 0,
    accounting: [{
        longTermCareInstitutionNumber: null,
        facilityBizType: null,
        name: null,
        startYearMonth: null,
        capacity: null,
        registrationCardFileStorageId: null,
        facilityBusinessId: null,
        price: null,
        options: [],
        registrationCard: {}
    }],
    withholding: {
        startYearMonth: null,
        capacity: null,
        price: 0,
        options: [{
            withholdingServiceType: null,
            price: 0,
        }]
    },
    usedAccounting: false,
    usedWithholding: false,
  },
  extra: {
    salesRepresentativeId: null,
    manageUserId: null,
  },


//   accountingfacilityBusinesses: [],
  
//   usedServiceInfoAccountingPrice: 0,
//   inputAgent: 0,
//   accountIntegration: 0,
//   sSIS: 0,
  
//   withholdingStartYearMonth: "",
//   withholdingCapacity: "",
//   usedServiceInfoWithholdingPrice: 0,
//   fourMajorInsurance: 0,
//   compactSalesRepresentativeId: 0,
//   manageUserId: 0,
//   name: "",
//   name2: "",
//   name3: "",
//   delivery: false,
//   type: [],
//   resource: "",
//   desc: "",
//   totalService: 0,
//   accFeeService: 0,
//   accBasicFee: "",
//   accInput: "",
//   accConsolidation: "",
//   acc4wc: "",
//   basicFee: "",
//   majorInsurance: "",
//   taxFeeSevice: 0,
//   checkBox: false,
//   checkBoxAccBasicFee: false,
//   checkBoxAccInput: false,
//   checkBoxAccConso: false,
//   checkBoxAcc4wc: false,
//   checkBoxMajorInsurance: false,
//   checkBoxBasicFee: false,
//   disableNumber1: false,
//   disableNumber2: false,
//   disableNumber3: false,
//   disableNumber4: false,
//   disableNumber5: false,
//   disableNumber6: false,
};
export const initialFormStateMomes = [
  {
    memoId: null,
    ownerUserId: 0,
    ownerName: "",
    ownerUsername: "",
    memo: "",
    createdAt: dayjs(new Date()).format("YYYY/MM/DD"),
    createdBy: "",
    updatedAt: dayjs(new Date()).format("YYYY/MM/DD"),
    updatedBy: "",
    ip: "",
    active: "",
  },
];
