import getElectronicFilingsByIncomeWagePaymentStatement from "./getElectronicFilingsByIncomeWagePaymentStatement";
import searchIncomeWagePaymentStatementElectronicFilings from "./searchIncomeWagePaymentStatementElectronicFilings";
import searchIncomeRetirementPaymentStatementElectronicFilings from "./searchIncomeRetirementPaymentStatementElectronicFilings";
import searchIncomeBusinessPaymentStatementElectronicFilings from "./searchIncomeBusinessPaymentStatementElectronicFilings";
import searchIncomeExtraPaymentStatementElectronicFilings from "./searchIncomeExtraPaymentStatementElectronicFilings";
import searchElectronicFilingFileProductions from "./searchElectronicFilingFileProductions";
const queries = {
  getElectronicFilingsByIncomeWagePaymentStatement: getElectronicFilingsByIncomeWagePaymentStatement,
  searchIncomeWagePaymentStatementElectronicFilings: searchIncomeWagePaymentStatementElectronicFilings,
  searchIncomeRetirementPaymentStatementElectronicFilings: searchIncomeRetirementPaymentStatementElectronicFilings,
  searchIncomeBusinessPaymentStatementElectronicFilings: searchIncomeBusinessPaymentStatementElectronicFilings,
  searchIncomeExtraPaymentStatementElectronicFilings: searchIncomeExtraPaymentStatementElectronicFilings,
  searchElectronicFilingFileProductions:searchElectronicFilingFileProductions
};

export default queries;
