export const employees = [{
  ID: 1,
  매니저: 'John',
  '연체(개월)': 28000000,
  관리시작일: '신청',
  사업자코드: 'CEO',
  상호: '1964/03/16',
  상태: '정상',
  주소: '1964/03/16',
  대표자: '1995/01/15',
  연락처: 'John has been in the Audio/Video industry since 1990. He has led DevAv as its CEO since 2003.\r\n\r\nWhen not working hard as the CEO, John loves to golf and bowl. He once bowled a perfect game of 300.',
  영업자: '351 S Hill St.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 5,
}, {
  ID: 2,
  매니저: 'Olivia',
  '연체(개월)': 3100000,
  상태: '해지',
  관리시작일: '심사중',
  사업자코드: 'Sales Assistant',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2012/05/14',
  연락처: 'Olivia loves to sell. She has been selling DevAV products since 2012. \r\n\r\nOlivia was homecoming queen in high school. She is expecting her first child in 6 months. Good Luck Olivia.',
  영업자: '807 W Paseo Del Mar',
  서비스: '회계3',
  이용료: 150000,
  해지일자: 5,
}, {
  ID: 3,
  매니저: 'Robert',
  '연체(개월)': 'Reagan',
  상태: '정상',
  관리시작일: '승인',
  사업자코드: 'CMO',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2002/11/08',
  연락처: 'Robert was recently voted the CMO of the year by CMO Magazine. He is a proud member of the DevAV Management Team.\r\n\r\nRobert is a championship BBQ chef, so when you get the chance ask him for his secret recipe.',
  영업자: '4 Westmoreland Pl.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 4,
}, {
  ID: 4,
  매니저: 'Greta',
  '연체(개월)': 'Sims',
  상태: '정상',
  관리시작일: '반려',
  사업자코드: 'HR Manager',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '1998/04/23',
  연락처: "Greta has been DevAV's HR Manager since 2003. She joined DevAV from Sonee Corp.\r\n\r\nGreta is currently training for the NYC marathon. Her best marathon time is 4 hours. Go Greta.",
  영업자: '1700 S Grandview Dr.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 11,
}, {
  ID: 5,
  매니저: 'Brett',
  '연체(개월)': 'Wade',
  상태: '정상',
  관리시작일: 'Mr.',
  사업자코드: 'IT Manager',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2009/03/06',
  연락처: 'Brett came to DevAv from Microsoft and has led our IT department since 2012.\r\n\r\nWhen he is not working hard for DevAV, he coaches Little League (he was a high school pitcher).',
  영업자: '1120 Old Mill Rd.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 13,
}, {
  ID: 6,
  매니저: 'Sandra',
  '연체(개월)': 'Johnson',
  상태: '정상',
  관리시작일: 'Mrs.',
  사업자코드: 'Controller',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2005/05/11',
  연락처: "Sandra is a CPA and has been our controller since 2008. She loves to interact with staff so if you've not met her, be certain to say hi.\r\n\r\nSandra has 2 daughters both of whom are accomplished gymnasts.",
  영업자: '4600 N Virginia Rd.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 44,
}, {
  ID: 7,
  매니저: 'Kevin',
  '연체(개월)': 'Carter',
  상태: '정상',
  관리시작일: 'Mr.',
  사업자코드: 'Shipping Manager',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2009/08/11',
  연락처: 'Kevin is our hard-working shipping manager and has been helping that department work like clockwork for 18 months.\r\n\r\nWhen not in the office, he is usually on the basketball court playing pick-up games.',
  영업자: '424 N Main St.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 5,
}, {
  ID: 8,
  매니저: 'Cynthia',
  '연체(개월)': 'Stanwick',
  상태: '정상',
  관리시작일: 'Ms.',
  사업자코드: 'HR Assistant',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2008/03/24',
  연락처: 'Cindy joined us in 2008 and has been in the HR department for 2 years. \r\n\r\nShe was recently awarded employee of the month. Way to go Cindy!',
  영업자: '2211 Bonita Dr.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 4,
}, {
  ID: 9,
  매니저: 'Kent',
  '연체(개월)': 'Samuelson',
  상태: '정상',
  관리시작일: 'Dr.',
  사업자코드: 'Ombudsman',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2009/04/22',
  연락처: 'As our ombudsman, Kent is on the front-lines solving customer problems and helping our partners 영업자 issues out in the field.    He is a classically trained musician and is a member of the Chamber Orchestra.',
  영업자: '12100 Mora Dr',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 26,
}, {
  ID: 10,
  매니저: 'Taylor',
  '연체(개월)': 'Riley',
  상태: '정상',
  관리시작일: 'Mr.',
  사업자코드: 'Network Admin',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2012/04/14',
  연락처: "If you are like the rest of us at DevAV, then you've probably reached out for help from Taylor. He does a great job as a member of our IT department.",
  영업자: '7776 Torreyson Dr',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 5,
}, {
  ID: 11,
  매니저: 'Sam',
  '연체(개월)': 'Hill',
  상태: '정상',
  관리시작일: 'Mr.',
  사업자코드: 'Sales Assistant',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2012/02/01',
  연락처: 'Sammy is proud to be a member of the DevAV team. He joined the team in 2012 and has been in the sales department from the beginning.\r\n\r\nHe has just picked up golf so you can find him on the links every weekend.',
  영업자: '645 Prospect Crescent',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 11,
}, {
  ID: 12,
  매니저: 'Kelly',
  '연체(개월)': 'Rodriguez',
  상태: '정상',
  관리시작일: 'Ms.',
  사업자코드: 'Support Assistant',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2012/10/13',
  연락처: "Kelly loves people and that's why she joined DevAV's support department. One of the funniest people in the company, she does stand-up on the weekends at the Laugh Factory.",
  영업자: '1601 W Mountain St.',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 5,
}, {
  ID: 13,
  매니저: 'Natalie',
  '연체(개월)': 'Maguirre',
  상태: '정상',
  관리시작일: 'Mrs.',
  사업자코드: 'Trainer',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2008/06/19',
  연락처: 'Natalie travels the US and teaches our partners how to explain the benefits of our products to customers.\r\n\r\nShe is a proud wife and mom and volunteers her time at the elementary school.',
  영업자: '6400 E Bixby Hill Rd',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 29,
}, {
  ID: 14,
  매니저: 'Walter',
  '연체(개월)': 'Hobbs',
  상태: '정상',
  관리시작일: 'Mr.',
  사업자코드: 'Programmer',
  상호: '1964/03/16',
  주소: '1964/03/16',
  대표자: '2011/02/17',
  연락처: "Walter has been developing apps and websites for DevAV since 2011. His passion is software and if you ever walk by his desk, you'll know why.\r\n\r\nWally once worked 72 hours straight - writing code and fixing bugs.",
  영업자: '10385 Shadow Oak Dr',
  서비스: '회계4',
  이용료: 150000,
  해지일자: 13,
}];

export const states = [{
  ID: 1,
  Name: 'Alabama',
}, {
  ID: 2,
  Name: 'Alaska',
}, {
  ID: 3,
  Name: 'Arizona',
}, {
  ID: 4,
  Name: 'Arkansas',
}, {
  ID: 5,
  Name: 'California',
}, {
  ID: 6,
  Name: 'Colorado',
}, {
  ID: 7,
  Name: 'Connecticut',
}, {
  ID: 8,
  Name: 'Delaware',
}, {
  ID: 9,
  Name: 'District of Columbia',
}, {
  ID: 10,
  Name: 'Florida',
}, {
  ID: 11,
  Name: 'Georgia',
}, {
  ID: 12,
  Name: 'Hawaii',
}, {
  ID: 13,
  Name: 'Idaho',
}, {
  ID: 14,
  Name: 'Illinois',
}, {
  ID: 15,
  Name: 'Indiana',
}, {
  ID: 16,
  Name: 'Iowa',
}, {
  ID: 17,
  Name: 'Kansas',
}, {
  ID: 18,
  Name: 'Kentucky',
}, {
  ID: 19,
  Name: 'Louisiana',
}, {
  ID: 20,
  Name: 'Maine',
}, {
  ID: 21,
  Name: 'Maryland',
}, {
  ID: 22,
  Name: 'Massachusetts',
}, {
  ID: 23,
  Name: 'Michigan',
}, {
  ID: 24,
  Name: 'Minnesota',
}, {
  ID: 25,
  Name: 'Mississippi',
}, {
  ID: 26,
  Name: 'Missouri',
}, {
  ID: 27,
  Name: 'Montana',
}, {
  ID: 28,
  Name: 'Nebraska',
}, {
  ID: 29,
  Name: 'Nevada',
}, {
  ID: 30,
  Name: 'New Hampshire',
}, {
  ID: 31,
  Name: 'New Jersey',
}, {
  ID: 32,
  Name: 'New Mexico',
}, {
  ID: 33,
  Name: 'New York',
}, {
  ID: 34,
  Name: 'North Carolina',
}, {
  ID: 35,
  Name: 'Ohio',
}, {
  ID: 36,
  Name: 'Oklahoma',
}, {
  ID: 37,
  Name: 'Oregon',
}, {
  ID: 38,
  Name: 'Pennsylvania',
}, {
  ID: 39,
  Name: 'Rhode Island',
}, {
  ID: 40,
  Name: 'South Carolina',
}, {
  ID: 41,
  Name: 'South Dakota',
}, {
  ID: 42,
  Name: 'Tennessee',
}, {
  ID: 43,
  Name: 'Texas',
}, {
  ID: 44,
  Name: 'Utah',
}, {
  ID: 45,
  Name: 'Vermont',
}, {
  ID: 46,
  Name: 'Virginia',
}, {
  ID: 47,
  Name: 'Washington',
}, {
  ID: 48,
  Name: 'West Virginia',
}, {
  ID: 49,
  Name: 'Wisconsin',
}, {
  ID: 50,
  Name: 'Wyoming',
}, {
  ID: 51,
  Name: 'North Dakota',
}];