name: build

on:
  push:
    branches-ignore:
      - "main"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: [ self-hosted, linux, x64, self-hosted-fe ]
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@bankda'
        env:
          NODE_AUTH_TOKEN: ${{secrets._AUTH_TOKEN}}

      # - name: Install Yarn
      #   run: npm install -g yarn

      # - name: Check yarn cache
      #   uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # - name: Install packages
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'
      #   run: yarn install
      #   env:
      #     CI: true
      #     NODE_AUTH_TOKEN: ${{secrets._AUTH_TOKEN}}

      # - name: Build vue
      #   run: yarn run build

      - name: Install packages
        run: npm install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets._AUTH_TOKEN}}

      - name: Build vue
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
