name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    # runs-on: [ self-hosted, linux, x64 ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@bankda'
        env:
          NODE_AUTH_TOKEN: ${{secrets._AUTH_TOKEN}}

      # - name: Install Yarn
      #   run: npm install -g yarn

      # - name: Check yarn cache
      #   uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # - name: Install packages
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'
      #   run: yarn install
      #   env:
      #     CI: true
      #     NODE_AUTH_TOKEN: ${{secrets._AUTH_TOKEN}}

      # - name: Build vue
      #   run: yarn run build

      - name: Install packages
        run: npm install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets._AUTH_TOKEN}}

      - name: Build vue
        run: npm run build

      - name: Upload S3 and Deploy CloudFront
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET_DEV }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
          invalidation: / *
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-2'
